# Generated by Django 4.2.9 on 2024-11-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_options_alter_game_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='games_photo', verbose_name='Фото'),
        ),
    ]
