# Generated by Django 4.2.9 on 2024-11-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_photo'),
        ('shop_cart', '0002_alter_shopcart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_cart', to='games.game'),
        ),
    ]
